INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Létající košťata', 'letajici-kostata', null, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Kouzelnické hůlky', 'kouzelnicke-hulky', null, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Oblečení', 'obleceni', null, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Čarodějnické knihy', 'carodejnicke-knihy', null, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Nimbus Racing Broom Company', 'nimbus-racing-broom-company', 12, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Cleansweep Broom Company', 'cleansweep-broom-company', 12, 1, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Comet Trading Company', 'comet-trading-company', 12, 0, 0);
INSERT INTO eshop.categories (name, slug, parent_id, showed, deleted) VALUES ('Kolejní hábity', 'kolejni-habity', 14, 1, 0);

INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Kolejní hábit Nebelvír', 'kolejni-habit-nebelvir', 'Elegantní a kouzelnický hábit Nebelvíru - symbol loajality, odvahy a moudrosti. Vynikající volba pro každého, kdo si chce přinést kousek kouzla do svého každodenního života.', '<p>Kolejní hábit Nebelvír je více než jen oblečení; je to symbol identity a příslušnosti k jedné z nejvzácnějších kolejí v kouzelnickém světě. Tento elegantní hábit je pečlivě navržen s důrazem na detail, aby přesně reflektoval charakter Nebelvíru - kolej, která si váží loajality, odvahy a moudrosti.</p>
<p>Výrazné barvy, charakteristický střih a kvalitní materiály společně tvoří toto unikátní oblečení, které vás vtáhne do atmosféry kouzelnického světa. Kolejní hábit Nebelvír je výjimečným způsobem, jak vyjádřit svou příslušnost k této ušlechtilé kolejní tradici.</p>
<p>Pro ty, kteří hledají víc než jen oblečení, je Kolejní hábit Nebelvír skvělou volbou. Je to investice do vlastního kouzelnického stylu a jedinečného spojení s hodnotami Nebelvíru. Oblečte se do této symbolické róby a nechte se unést kouzlem Nebelvíru ve vašem srdci.</p>', '2024-01-11 23:46:27', '2024-01-12 01:06:14', 20, 19, 1, 0, 10, 3, 1);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Kolejní nábit Zmijozel', 'kolejni-nabit-zmijozel', 'Elegance s nádechem tajemství - Kolejní hábit Zmijozel. Výrazné barvy a sofistikovaný střih, který zvýrazňuje chytrost a ambice. Dokonalý oděv pro ty, kteří si chtějí užít stylový a kouzelnický život.', '<p>Kolejní hábit Zmijozel je vyjádřením výjimečnosti a ambicí, které jsou charakteristické pro tuto ušlechtilou kolej. Elegantní střih, výrazné barvy a kvalitní provedení tvoří unikátní kus oděvu, který září sofistikovaností a tajemstvím.</p>
<p>Tento hábit je navržen tak, aby podtrhl jedinečnost a chytrost Zmijozelu, a zároveň poskytoval pohodlí a styl. Každý detail hábitu zdůrazňuje tradice a hodnoty této kolejní společnosti. Pro ty, kteří si přejí vyjádřit svou oddanost Zmijozelu, je tento hábit nezbytným doplňkem k jejich kouzelnickému stylu.</p>
<p>Oblečení Kolejní hábit Zmijozel je více než jen oděv; je to výraz identity a hrdosti na to, být součástí jedné z nejvýznamnějších kolejí s kouzelnickou historií. Vstupte do světa tajemství a ambicí s tímto exkluzivním hábitem, který zvýrazní vaši kouzelnickou osobnost.</p>', '2024-01-11 23:52:00', '2024-01-12 01:08:15', 20, 19, 1, 0, 11, 8, 2);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Kolejní hábit Havraspár', 'kolejni-habit-havraspar', 'Hrdost, elegance a tradice spojené v jednom - Kolejní hábit Havraspár. Pro ty, kteří ctí hodnoty vzdělání, moudrosti a odvahy.', '<p>Kolejní hábit Havraspár je vyjádřením intelektu, moudrosti a odhodlání. Tento symbolický kousek oděvu spojuje hrdost s elegancí, čímž vytváří unikátní zážitek pro ty, kteří se chtějí identifikovat s hodnotami Havraspáru.</p>
<p>S precizním střihem a výběrem barev reflektujících tradice kolejí Havraspáru nabízí tento hábit nejen stylový vzhled, ale také pohodlí a kvalitu provedení. Pro každého, kdo ctí vzdělání, intelektuální růst a vznešenost, je Kolejní hábit Havraspár skvělou volbou.</p>
<p>Každý detail hábitu nese důležitou symboliku, ať už jde o logo kolejního domu nebo specifický střih, který zdůrazňuje osobitost Havraspáru. Oblečení tohoto hábitu je nejen výrazem hrdosti na vlastní kolej, ale také způsobem, jak projevit vášeň pro vzdělání, moudrost a výjimečnost.</p>', '2024-01-11 23:53:21', '2024-01-12 01:09:47', 20, 19, 1, 0, 9, 15, 2);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Kolejní hábit Mrzimor', 'kolejni-habit-mrzimor', 'Elegance s temným šarmem - Kolejní hábit Mrzimor. Oblečte se do tohoto exkluzivního oděvu, který v sobě nese mystiku a jedinečnost.', '<p>Kolejní hábit Mrzimor spojuje temné tóny s výrazným designem, vytvářející unikátní a působivý kousek oděvu. Tento hábit je navržen s ohledem na výjimečnost kolejního domu Mrzimor, který je známý pro svou odvahu, nekompromisnost a touhu po síle.</p>
<p>Elegantní střih a kvalitní materiály zvýrazňují jedinečný charakter tohoto hábitu, který se stává výrazem individuality a mystiky. Získáte nejen oblečení, ale také symbolický prvek spojený s temným šarmem Mrzimoru.</p>
<p>Oblečte se do Kolejního hábitu Mrzimor a nechte se unést do atmosféry síly a odvahy. Pro ty, kteří se chtějí vyjádřit prostřednictvím kouzelnického stylu s temným nádechem, je tento hábit nezbytným doplňkem k jejich osobnosti.</p>', '2024-01-11 23:55:05', '2024-01-12 01:10:23', 20, 19, 1, 0, 12, 5, 2);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Nimbus 1000', 'nimbus-1000', 'Létající koště Nimbus 1000 - kouzelnická dokonalost v podobě jedinečného doplňku. Elegantní design, kvalitní provedení a autentický pocit přinášejí kouzlo každodenních okamžiků. Pro všechny, kteří hledají magii ve svém životě.', '<p>Vstupte do světa kouzelnické elegance s létajícím koštětem Nimbus 1000. Jeho jedinečný design a kvalitní zpracování nejenže dotvářejí atmosféru mističky, ale také vám umožňují prožívat každodenní okamžiky s nádechem magie.</p>
<p>Nimbus 1000 není pouhým předmětem, je to umělecké dílo, které spojuje precizní řemeslnou práci s vizuální elegancí. Ergonomický tvar rukojeti a pečlivě zpracované detaily vytvářejí autentický pocit a zároveň dodávají prostoru kouzelnický nádech.</p>
<p>Toto létající koště není jen dekorační prvek, ale zároveň symbol osobní svobody a touhy po dobrodružství. Jeho pohyblivost a lehkost vám umožní uniknout rutině a prozkoumat svět s novým pohledem. Nimbus 1000 je více než jen doplněk, je to prostředek, jak přinést kouzlo do každého okamžiku vašeho života.</p>', '2024-01-12 00:02:56', null, 10, 16, 1, 0, 35, 12, 4);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Nimbus 1700', 'nimbus-1700', 'Inovativní létající koště Nimbus 1700 přináší vzrušující dobrodružství do každodenních chvil. S elegantním designem a technologickými vylepšeními je dokonalým spojením stylového doplňku a kouzelnického zážitku.', '<p>Ponořte se do světa magie s létajícím koštětem Nimbus 1700, které znamená revoluci v kouzelnických doplňcích. Jeho inovativní design spojený s pokročilými technologickými prvky zajišťuje nejen dokonalou pohyblivost, ale také bezpečný a pohodlný zážitek z létání.</p>
<p>Nimbus 1700 přináší do světa magie nový rozměr. Elegantní ergonomický design rukojeti a aerodynamické tvary metly jsou precizně navrženy tak, aby poskytovaly optimální ovladatelnost a komfort při každém vzletu. Integrované technologické vylepšení dodávají košti sílu a rychlost, kterou ocení každý odvážlivec.</p>
<p>Toto létající koště není pouze doplňkem, ale vstupenkou do světa vzdušných dobrodružství. Bezpečný a spolehlivý mechanismus zajišťuje, že každý let je bezstarostným výletem do neznámého. Nimbus 1700 - dokonalé spojení elegance, technologie a kouzla v jednom.</p>', '2024-01-12 00:06:30', null, 15, 16, 1, 0, 42, 16, 4);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Nimbus 2000', 'nimbus-2000', 'Revoluční létající koště Nimbus 2000 přináší do vašeho života magii a dobrodružství. Elegantní design a technologické inovace spojené v jednom kouzelnickém doplňku.', '<p>Otevřete brány nebes s létajícím koštětem Nimbus 2000, které znamená vrchol kouzelnické elegance a technologického pokroku. Jeho aerodynamický design a precizní zpracování nejen oslní svým vzhledem, ale také zajišťuje optimální ovladatelnost při každém letu.</p>
<p>Nimbus 2000 není jen létajícím doplňkem, je to kouzelnický průvodce vzdušnými dobrodružstvími. Ergonomická rukojeť a pohyblivá metla jsou vytvořeny s ohledem na maximální komfort a bezpečnost při každém vzletu. Integrované technologické prvky dodávají košti sílu a stabilitu, což z něj činí ideálního společníka pro odvážné cestovatele vzdušnými prostory.</p>
<p>S Nimbus 2000 přinášíte do svého života kousek magie, který transformuje každý den na dobrodružství. Prožijte vzlety do neznáma s kouzelnickým koštětem, který spojuje tradici, design a technologii v jedinečném kouzelnickém zážitku.</p>', '2024-01-12 00:08:32', null, 16, 16, 1, 0, 53, 10, 5);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Cleansweep 1', 'cleansweep-1', 'Létající koště Cleansweep One přináší do vašeho života novou dimenzi dobrodružství. S moderním designem a inovativními prvky je ideálním společníkem pro všechny, kdo hledají pohodlný a elegantní způsob pohybu.', '<p>Osvoboďte svou duši dobrodružstvím s létajícím koštětem Cleansweep One. Jeho moderní design a inovativní technologické prvky přinášejí do vašeho každodenního života nový smysl pro svobodu a eleganci.</p>
<p>Cleansweep One není jen prostředkem k pohybu, je to umělecké dílo spojující v sobě estetiku, funkčnost a pohodlí. Ergonomická konstrukce a pohyblivá metla zajišťují optimální ovladatelnost a bezproblémový let. S integrovanými technologickými vylepšeními je tento model nejen spolehlivým dopravním prostředkem, ale také stylovým symbolem svobody.</p>
<p>Cleansweep One je více než jen doplněk, je to cesta ke světu dobrodružství. Bezpečný, elegantní a plný šarmu, toto létající koště vás provede vzdušnými stezkami s lehkostí a grácií. Vstupte do nového věku s Cleansweep One a objevte kouzlo pohybu ve stylu.</p>', '2024-01-12 00:12:25', null, 8, 17, 1, 0, 25, 12, 5);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Cleansweep 2', 'cleansweep-2', 'Létající koště Cleansweep Two - inovativní design a technologické prvky spojené v jednom pohodlném a stylovém doplňku pro každodenní dobrodružství.', '<p>Osvoboďte se od země s létajícím koštětem Cleansweep Two, které spojuje bezpečnost, pohodlí a elegance ve svěžím designu. Toto kouzelnické dopravní prostředek není pouze prostředkem k cestování, ale symbolem svobody a inovace.</p>
<p>Cleansweep Two se vyznačuje moderním designem, který zdůrazňuje ergonomii a pohodlí. Jeho pohyblivá metla a technologické inovace zajišťují plynulý let bez kompromisů. S lehkostí a grácií vám umožní prozkoumat okolní krajinu a zažívat dobrodružství ve vzduchu.</p>
<p>Toto létající koště není jen prostředkem k pohybu, ale také módním a stylovým doplňkem pro každého, kdo ocení spojení estetiky a praktičnosti. Cleansweep Two je představitelem moderní éry létání, která nabízí bezpečnost, pohodlí a neomezené možnosti pro každodenní dobrodružství.</p>', '2024-01-12 00:13:58', null, 16, 17, 1, 0, 26, 15, 18);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Průvodce přeměňováním pro začátečníky', 'pruvodce-premenovanim-pro-zacatecniky', 'Vstupte do fascinujícího světa magie s knihou "Průvodce přeměňováním pro začátečníky". Skvělý průvodce pro ty, kteří touží po objevování kouzelnických dovedností a tajemství.', '<p>Tato kniha otevírá dveře kouzelnického umění před těmi, kteří se chtějí ponořit do světa přeměňování. "Průvodce přeměňováním pro začátečníky" je komplexním průvodcem pro ty, kteří hledají hlubší porozumění a ovládnutí magických dovedností.</p>
<p>Autorka se věnuje nejen praktickým aspektům přeměňování, ale také historii, filozofii a etice spojené s tímto fascinujícím oborem magie. Každá stránka nabízí čtenáři podrobný pohled na techniky, cvičení a rituály, které pomáhají rozvinout a zdokonalit schopnosti přeměňování.</p>
<p>"Průvodce přeměňováním pro začátečníky" není pouze knihou o kouzlech; je to průvodce osobním objevováním, který nabízí inspiraci, povzbuzení a návod, jak proniknout do hlubin vlastní magické síly. Ideální volba pro ty, kteří touží po tom stát se mistrem přeměňování a otevřít dveře k neomezeným možnostem magie ve svém životě.</p>', '2024-01-12 00:27:30', null, 30, 20, 1, 0, 1, 1, 1);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Pokročilý průvodce přeměňováním', 'pokrocily-pruvodce-premenovanim', 'Vstupte do tajemného světa magie s knihou "Pokročilý průvodce přeměňováním". Skvělý průvodce pro ty, kteří se chtějí posunout dál ve svých kouzelnických dovednostech.', '<p>Tato kniha přináší rozšířené a hlubší poznatky do oblasti přeměňování pro ty, kteří touží po zdokonalení svých magických schopností. "Pokročilý průvodce přeměňováním" je komplexním průvodcem pro ty, kteří již ovládají základy a hledají pokročilé techniky a návody.</p>
<p>Autor/autorka se detailně zabývá sofistikovanými metodami, tajnými rituály a pokročilými strategiemi v oblasti přeměňování. Knížka není jen praktickým průvodcem, ale i inspirací pro ty, kteří chtějí prozkoumat hranice svých kouzelnických schopností. Každá kapitola poskytuje hluboké pochopení magického světa a nasměrování na cestu k mistrovství v oboru přeměňování.</p>
<p>"Pokročilý průvodce přeměňováním" je klíčem k odemykání potenciálu magie, který spočívá v nás všech. Ideální volba pro ty, kteří jsou připraveni jít za hranice obvyklého a prohloubit svou kouzelnickou cestu do nových dimenzí.</p>', '2024-01-12 00:31:22', null, 15, 20, 1, 0, 2, 1, 0);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Průvodce přeměňováním pro středně pokročilé', 'pruvodce-premenovanim-pro-stredne-pokrocile', 'Prohlubte své kouzelnické schopnosti s knihou "Průvodce přeměňováním pro středně pokročilé". Skvělý průvodce pro ty, kteří chtějí posunout své dovednosti na novou úroveň.', '<p>Tato kniha je určena těm, kteří již ovládají základní principy přeměňování a hledají další pokročilé techniky a tipy. "Průvodce přeměňováním pro středně pokročilé" vás provede dalším stupněm kouzelnického umění a pomůže vám objevit nové možnosti v oblasti proměny a transformace.</p>
<p>Autor/autorka se zaměřuje na středně pokročilé metody přeměňování, představuje různé přístupy a strategie pro zdokonalení dovedností. Každá kapitola knihy nabízí praktické rady, cvičení a příklady, které vám pomohou posílit vaše kouzelnické schopnosti. "Průvodce přeměňováním pro středně pokročilé" slouží jako inspirace a průvodce pro ty, kteří chtějí prohloubit svou magickou cestu.</p>
<p>Tato kniha je klíčem k otevření dveří kouzelnického světa pro ty, kteří touží po dalším rozvoji svých magických dovedností. Ideální volba pro středně pokročilé kouzelníky, kteří jsou připraveni na další úroveň v jejich magickém putování.</p>', '2024-01-12 00:34:10', null, 16, 20, 1, 0, 3, 2, 1);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Základní obrana proti černé magii', 'zakladni-obrana-proti-cerne-magii', 'Ochrana a síla spojené v jedné knize. "Základní obrana proti černé magii" je klíčovým průvodcem pro ty, kteří chtějí porozumět a bránit se proti temným silám.', '<p>Tato kniha je komplexním průvodcem pro každého, kdo se zajímá o obranu proti černé magii. Bez ohledu na to, zda jste začátečník nebo zkušený kouzelník, "Základní obrana proti černé magii" poskytuje nezbytné informace, techniky a rituály k ochraně sebe a svého okolí před temnými silami.</p>
<p>Autor/autorka se věnuje nejen praktickým strategiím pro odvrácení negativních energií, ale také rozvíjí pochopení etických aspektů v obraně proti černé magii. Každá kapitola nabízí konkrétní rady, vizualizace a cvičení, které vám pomohou posílit svou energetickou ochranu.</p>
<p>"Základní obrana proti černé magii" není pouze knihou o kouzlech; je to průvodce osobním rozvojem a obranou proti nežádoucím vlivům. Ideální volba pro ty, kteří hledají prostředky k posílení své duševní a energetické odolnosti v tváři magických výzev života.</p>', '2024-01-12 00:38:10', null, 22, 21, 1, 0, 4, 2, 0);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Průvodce sebeobranou proti černé magii', 'pruvodce-sebeobranou-proti-cerne-magii', 'Ochrana a síla spojené v jednom průvodci. Tato kniha vám poskytne klíčové dovednosti a strategie k sebeobraně před temnými silami.', '<p>"Průvodce sebeobranou proti černé magii" je komplexním průvodcem pro každého, kdo touží po individuální ochraně a odolnosti vůči temným energiím. Tato kniha poskytuje nejen praktické techniky sebeobrany, ale také hlubší porozumění principům energetické ochrany a odhalení temných intrik a vlivů.</p>
<p>Autor/autorka prochází různými aspekty sebeobrany, včetně psychologických, fyzických a energetických technik, které vám umožní aktivně se bránit proti negativním silám kolem vás. Každá kapitola je plná praktických cvičení, rad a příběhů, které vám pomohou vyvinout sílu a sebedůvěru v oblasti sebeobrany.</p>
<p>"Průvodce sebeobranou proti černé magii" není pouze knihou o kouzlech; je to průvodce, který vám pomůže objevit vaši vlastní sílu a naučit se efektivně reagovat na výzvy spojené s negativními energiemi. Ideální volba pro ty, kteří chtějí ovládnout dovednosti sebeobrany a posílit svou odolnost v každodenním životě.</p>', '2024-01-12 00:55:24', null, 23, 21, 1, 0, 3, 4, 2);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Pokročilá obrana proti černé magii', 'pokrocila-obrana-proti-cerne-magii', 'Staňte se mistrem svého osudu s touto knihou, která vám otevře dveře k pokročilým strategiím a obranným dovednostem proti temným silám.', '<p>"Pokročilá obrana proti černé magii" představuje komplexní průvodce pro ty, kteří hledají vyšší úroveň ochrany před negativními energiemi. Autor/autorka se v tomto díle věnuje sofistikovaným a pokročilým strategiím obrany, které vás naučí nejen odvracet temné vlivy, ale také aktivně pracovat s energií a sílou své mysli.</p>
<p>Kniha podrobně rozebírá techniky energetické ochrany, vizualizace, meditace a rituály, které vám pomohou vybudovat neprostupný štít proti černé magii. Bez ohledu na to, zda jste začátečník či zkušený praktikující, každá kapitola nabízí hlubší vhled do světa obrany a posilování duševní odolnosti.</p>
<p>"Pokročilá obrana proti černé magii" je kniha pro ty, kteří jsou připraveni vzít v ruce svou osudovou hůlku a aktivně se postavit všem výzvám spojeným s negativními energiemi a temnými silami.</p>', '2024-01-12 01:02:06', null, 17, 21, 1, 0, 4, 3, 1);
INSERT INTO eshop.products (name, slug, summary, description, created, updated, stock, category_id, showed, deleted, galleon_price, sickle_price, knut_price) VALUES ('Kouzelné recepty a lektvary', 'kouzelne-recepty-a-lektvary', 'Otevřete bránu kouzelnému světu s touto knihou plnou tajemných receptů a lektvarů, které probudí vaši kouzelnickou kreativitu.', '<p>Tato kniha je průvodcem do světa nekonečných možností kouzelnických receptů a lektvarů. Autor/autorka přináší jedinečný mix tradičních a moderních receptů, které vás provedou různými aspekty kouzelnické kuchyně.</p>
<p>Od elixírů pro posílení duše až po tajemné nápoje, které probudí vaše smysly, každá kapitola je plná fascinujících receptů, kouzelnických ingrediencí a návodů k vytvoření magických lektvarů ve vaší vlastní kuchyni. Kniha není jen o vaření; je to průvodce kouzelnickým uměním, který vás inspiruje k objevování nových chutí a kreativnímu experimentování s magií přírody.</p>
<p>"Kouzelné recepty a lektvary" je ideální volbou pro ty, kteří chtějí oživit svou kouzelnickou stránku a prozkoumat, jak může magie obohatit každodenní život. Každý recept je příležitostí k vyjádření vaší kreativity a kouzelnické intuice, ať už jste začátečník nebo zkušený kouzelník.</p>', '2024-01-12 01:05:01', null, 15, 22, 1, 0, 3, 3, 1);
